function _precompile_()
    ccall(:jl_generating_output, Cint, ()) == 1 || return nothing
    precompile(Tuple{typeof(cell_centroid),PolytopalMesh{2,Float64,jFEMTools.Cell{2,4,4,1}},Int64})
    precompile(Tuple{Type{jFEMTools.QuadratureRule{2,jFEMTools.RefSimplex,T} where T},jFEMTools.Strang,Int64})
    precompile(Tuple{typeof(jFEMTools.gradient_value),jFEMTools.Monomials{2,1,Float64},Int64,Tensors.Tensor{1,2,Float64,2}})
    precompile(Tuple{typeof(jFEMTools.mapPointsFromReference),Type{jFEMTools.RefSimplex},Array{Tensors.Tensor{1,2,Float64,2},1},Array{Tensors.Tensor{1,2,Float64,2},1}})
    precompile(Tuple{Type{jFEMTools.Monomials},Int64,Int64,Tensors.Tensor{1,2,Float64,2},Float64})
    precompile(Tuple{typeof(jFEMTools.value),jFEMTools.Monomials{2,1,Float64},Int64,Tensors.Tensor{1,2,Float64,2}})
    precompile(Tuple{typeof(jFEMTools.getverticesindices),PolytopalMesh{2,Float64,jFEMTools.Cell{2,4,4,1}},jFEMTools.EdgeIndex})
    precompile(Tuple{Type{DofHandler},PolytopalMesh{2,Float64,jFEMTools.Cell{2,3,3,1}},TrialFunction{PoissonVirtualElement{2}}})
    precompile(Tuple{typeof(rectangle_mesh),Type{jFEMTools.Cell{2,3,3,1}},Tuple{Int64,Int64},Tensors.Tensor{1,2,Float64,2},Tensors.Tensor{1,2,Float64,2}})
    precompile(Tuple{typeof(cell_diameter),PolytopalMesh{2,Float64,jFEMTools.Cell{2,3,3,1}},Int64})
    precompile(Tuple{typeof(jFEMTools.gradient_value),jFEMTools.Monomials{2,2,Float64},Int64,Tensors.Tensor{1,2,Float64,2}})
    precompile(Tuple{typeof(rectangle_mesh),Type{jFEMTools.Cell{2,4,4,1}},Tuple{Int64,Int64},Tensors.Tensor{1,2,Float64,2},Tensors.Tensor{1,2,Float64,2}})
    precompile(Tuple{typeof(apply!),SparseMatrixCSC{Bool,Int64},Array{Float64,1},Dirichlet{Float64}})
    precompile(Tuple{typeof(jFEMTools.value),jFEMTools.Monomials{2,2,Float64},Int64,Tensors.Tensor{1,2,Float64,2}})
    precompile(Tuple{typeof(get_vertices_matrix),PolytopalMesh{2,Float64,jFEMTools.Cell{2,3,3,1}}})
    precompile(Tuple{typeof(jFEMTools.create_sparsity_pattern),DofHandler{2,Float64}})
    precompile(Tuple{typeof(cell_volume),PolytopalMesh{2,Float64,jFEMTools.Cell{2,3,3,1}},Int64})
    precompile(Tuple{typeof(jFEMTools.get_2Dtesselation),Array{Tensors.Tensor{1,2,Float64,2},1}})
    precompile(Tuple{typeof(assemble!),jFEMTools.Assembler{Float64},Array{Int64,1},Array{Float64,2}})
    precompile(Tuple{typeof(cell_volume),PolytopalMesh{2,Float64,jFEMTools.Cell{2,4,4,1}},Int64})
    precompile(Tuple{typeof(jFEMTools.value),jFEMTools.Monomials{2,0,Float64},Int64,Tensors.Tensor{1,2,Float64,2}})
end
